import fs from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const contentRoot = path.join(repoRoot, 'docs/econ/content/economic_observation')
const outIndexMd = path.join(repoRoot, 'docs/econ/content/index.md')
const outSidebar = path.join(repoRoot, 'docs/.vitepress/generated/econSidebar.mjs')

function walk(dir) {
  const out = []
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    if (ent.name.startsWith('.')) continue
    const p = path.join(dir, ent.name)
    if (ent.isDirectory()) out.push(...walk(p))
    else if (ent.isFile() && ent.name.toLowerCase().endsWith('.md')) out.push(p)
  }
  return out
}

function toPosix(p) {
  return p.split(path.sep).join('/')
}

function stripMd(rel) {
  return rel.replace(/\.md$/i, '')
}

function mdLinkFromRel(rel) {
  return './economic_observation/' + toPosix(stripMd(rel))
}

function titleFromRel(rel) {
  return path.basename(rel, '.md')
}

const filesAbs = fs.existsSync(contentRoot) ? walk(contentRoot) : []
const filesRel = filesAbs.map(f => path.relative(contentRoot, f))

// Group by first segment
const groups = new Map()
for (const rel of filesRel) {
  const seg = rel.split(path.sep)[0] || ''
  const group = seg.toLowerCase() === 'readme.md' ? 'ROOT' : seg
  if (!groups.has(group)) groups.set(group, [])
  groups.get(group).push(rel)
}

const lines = []
lines.push('---')
lines.push('title: 经济观察 · 内容目录')
lines.push('---')
lines.push('')
lines.push('# 内容目录')
lines.push('')
lines.push('本页由构建脚本自动生成：扫描 `economic_observation` 仓库并生成可点击目录。')
lines.push('')

if (groups.has('ROOT')) {
  const rootReadme = groups.get('ROOT').find(x => x.toLowerCase() === 'readme.md')
  if (rootReadme) {
    lines.push('## 总览')
    lines.push('')
    lines.push('<div class="dir-list">')
    lines.push(`  <a class="dir-item" href="${mdLinkFromRel(rootReadme)}">README</a>`)
    lines.push('</div>')
    lines.push('')
  }
}

const groupNames = [...groups.keys()]
  .filter(g => g !== 'ROOT')
  .sort((a, b) => a.localeCompare(b, 'zh-Hans-CN'))

for (const g of groupNames) {
  lines.push(`## ${g}`)
  lines.push('')
  const rels = groups.get(g)
    .filter(r => !r.toLowerCase().endsWith('/readme.md'))
    .sort((a, b) => a.localeCompare(b, 'zh-Hans-CN'))

  lines.push('<div class="dir-list">')
  for (const rel of rels) {
    lines.push(`  <a class="dir-item" href="${mdLinkFromRel(rel)}">${titleFromRel(rel)}</a>`)
  }
  lines.push('</div>')
  lines.push('')
}

fs.mkdirSync(path.dirname(outIndexMd), { recursive: true })
fs.writeFileSync(outIndexMd, lines.join('\n'), 'utf-8')

const sidebarObj = {
  '/econ/': [
    {
      text: '经济观察',
      items: [
        { text: '导览', link: '/econ/' },
        { text: '内容目录', link: '/econ/content/' }
      ]
    }
  ]
}

fs.mkdirSync(path.dirname(outSidebar), { recursive: true })
fs.writeFileSync(
  outSidebar,
  `// Auto-generated by scripts/generate_econ_index.mjs\nexport const econSidebar = ${JSON.stringify(sidebarObj, null, 2)}\n`,
  'utf-8'
)

console.log(`Generated: ${path.relative(repoRoot, outIndexMd)} (${filesRel.length} md scanned)`) 
