import fs from 'node:fs'
import path from 'node:path'
import { execSync } from 'node:child_process'

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const contentRoot = path.join(repoRoot, 'docs/econ/content/economic_observation')
const outIndexMd = path.join(repoRoot, 'docs/econ/content/index.md')
const outSidebar = path.join(repoRoot, 'docs/.vitepress/generated/econSidebar.mjs')
const outHomeRecent = path.join(repoRoot, 'docs/.vitepress/generated/recentEconUpdates.mjs')

function walk(dir) {
  const out = []
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    if (ent.name.startsWith('.')) continue
    const p = path.join(dir, ent.name)
    if (ent.isDirectory()) out.push(...walk(p))
    else if (ent.isFile() && ent.name.toLowerCase().endsWith('.md')) out.push(p)
  }
  return out
}

function toPosix(p) {
  return p.split(path.sep).join('/')
}

function stripMd(rel) {
  return rel.replace(/\.md$/i, '')
}

function docLinkFromRel(rel) {
  return '/econ/content/economic_observation/' + toPosix(stripMd(rel))
}

function mdLinkFromRel(rel) {
  return './economic_observation/' + toPosix(stripMd(rel))
}

function titleFromRel(rel) {
  return path.basename(rel, '.md')
}

function gitDate(absPath) {
  try {
    const out = execSync(`git log -1 --format=%ci -- "${absPath}"`, {
      cwd: contentRoot,
      encoding: 'utf-8',
      timeout: 5000
    }).trim()
    // 输出格式: 2026-03-29 03:04:00 +0000 → 取前10字符
    return out ? out.slice(0, 10) : null
  } catch {
    return null
  }
}

const filesAbs = fs.existsSync(contentRoot) ? walk(contentRoot) : []
const filesRel = filesAbs.map(f => path.relative(contentRoot, f))

// Group by first segment
const groups = new Map()
for (const rel of filesRel) {
  const seg = rel.split(path.sep)[0] || ''
  const group = seg.toLowerCase() === 'readme.md' ? 'ROOT' : seg
  if (!groups.has(group)) groups.set(group, [])
  groups.get(group).push(rel)
}

// -------- 1) Generate auto index page (Markdown) --------
const lines = []
lines.push('---')
lines.push('title: 经济观察 · 内容目录')
lines.push('---')
lines.push('')
lines.push('# 内容目录')
lines.push('')
lines.push('本页由构建脚本自动生成：扫描 `economic_observation` 仓库并生成可点击目录。')
lines.push('')

if (groups.has('ROOT')) {
  const rootReadme = groups.get('ROOT').find(x => x.toLowerCase() === 'readme.md')
  if (rootReadme) {
    lines.push('## 总览')
    lines.push('')
    lines.push('<div class="dir-list">')
    lines.push(`  <a class="dir-item" href="${mdLinkFromRel(rootReadme)}">README</a>`)
    lines.push('</div>')
    lines.push('')
  }
}

const groupNames = [...groups.keys()]
  .filter(g => g !== 'ROOT')
  .sort((a, b) => a.localeCompare(b, 'zh-Hans-CN'))

for (const g of groupNames) {
  lines.push(`## ${g}`)
  lines.push('')
  const rels = groups.get(g)
    .filter(r => !r.toLowerCase().endsWith('/readme.md'))
    .sort((a, b) => a.localeCompare(b, 'zh-Hans-CN'))

  lines.push('<div class="dir-list">')
  for (const rel of rels) {
    lines.push(`  <a class="dir-item" href="${mdLinkFromRel(rel)}">${titleFromRel(rel)}</a>`)
  }
  lines.push('</div>')
  lines.push('')
}

fs.mkdirSync(path.dirname(outIndexMd), { recursive: true })
fs.writeFileSync(outIndexMd, lines.join('\n'), 'utf-8')

// -------- 2) Generate VitePress sidebar for econ pages --------
const sidebarGroups = []
for (const g of groupNames) {
  const rels = groups.get(g)
    .filter(r => !r.toLowerCase().endsWith('/readme.md'))
    .sort((a, b) => a.localeCompare(b, 'zh-Hans-CN'))

  const items = rels.map(rel => ({ text: titleFromRel(rel), link: docLinkFromRel(rel) }))

  if (items.length) {
    sidebarGroups.push({ text: g, collapsed: true, items })
  }
}

// Also add root-level files (not in subdirectories) as a flat group
const rootFiles = (groups.get('ROOT') || [])
  .filter(r => r.toLowerCase() !== 'readme.md')
  .sort((a, b) => a.localeCompare(b, 'zh-Hans-CN'))
if (rootFiles.length) {
  const items = rootFiles.map(rel => ({ text: titleFromRel(rel), link: docLinkFromRel(rel) }))
  sidebarGroups.unshift({ text: '通用', collapsed: false, items })
}

const sidebarObj = {
  '/econ/': [
    {
      text: '经济观察',
      items: [
        { text: '导览', link: '/econ/' },
        { text: '内容目录', link: '/econ/content/' }
      ]
    },
    ...sidebarGroups
  ]
}

fs.mkdirSync(path.dirname(outSidebar), { recursive: true })
fs.writeFileSync(
  outSidebar,
  `// Auto-generated by scripts/generate_econ_index.mjs\nexport const econSidebar = ${JSON.stringify(sidebarObj, null, 2)}\n`,
  'utf-8'
)

// -------- 3) Generate "recent updates" list for homepage --------
// 用 git commit 日期代替文件名日期
const withDates = filesRel
  .filter(r => !r.toLowerCase().endsWith('/readme.md'))
  .map(rel => ({
    rel,
    date: gitDate(path.join(contentRoot, rel))
  }))
  .filter(x => x.date)
  .sort((a, b) => b.date.localeCompare(a.date))

const recent = withDates.slice(0, 8).map(x => ({
  text: titleFromRel(x.rel),
  date: x.date,
  link: docLinkFromRel(x.rel)
}))

fs.mkdirSync(path.dirname(outHomeRecent), { recursive: true })
fs.writeFileSync(
  outHomeRecent,
  `// Auto-generated by scripts/generate_econ_index.mjs\nexport const recentEconUpdates = ${JSON.stringify(recent, null, 2)}\n`,
  'utf-8'
)

console.log(`Generated: ${path.relative(repoRoot, outIndexMd)} (${filesRel.length} md scanned)`)
